### ISSUE TITLE
Validate proper naming for Composite resources

### ISSUE THREAD

**Issue by stevendborrelli** [upbound/up#140]
### What problem are you facing?

Environment: 
Up: version 0.7.0, 
VS-code plugin 0.0.5. 

When building compositions the following error is not highlighted:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: iothubcomposites.mycompany.io

spec:
  group: .io
  names:
    kind: IOTHubComposite
    plural: IOTHubComposites
  claimNames:
    kind: IOTHub
    plural: IOTHubs
```

Will get an error from the controller:

```
IOTHubs.mycompany.io" is invalid: [metadata.name: Invalid value: "IOTHubs.mycompany.io": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.names.plural: Invalid value: "IOTHubs": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')]
```

### How could Upbound help solve your problem?

The language server should match name validation of XR resources.
