### ISSUE TITLE
Error refers to XRD when Composition is issue

### ISSUE THREAD

**Issue by natereid72** [upbound/up#167]
### What happened?

Modified Composition, missed an indent on a patches section, used `up xpkg build` and received error `up: error: failed to build package: failed to parse package: {path:/Users/nate/platform-ref-azure/cluster/aks/definition.yaml position:0}: yaml: line 19: did not find expected '-' indicator`.

Fixed Composition and error was resolved.

Epic #

### How can we reproduce it?

Build ConfigurationPackage with the following manifests:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclusters.azure.platformref.crossplane.io
  annotations:
    upbound.io/ui-schema: |-
      ---
      configSections:
      - title: Cluster Info
        description: Information about this cluster
        items:
        - name: id
          controlType: singleInput
          type: string
          path: ".spec.id"
          title: Cluster Ref Name
          description: Cluster ID that other objects will use to refer to this cluster
          default: platform-ref-azure
          validation:
          - required: true
            customError: Cluster ID is required.
        - name: writeSecretRef
          controlType: singleInput
          type: string
          path: ".spec.writeConnectionSecretToRef.name"
          title: Connection Secret Ref
          description: name of the secret to write to this namespace
          default: cluster-conn
          validation:
          - required: true
      - title: Cluster Nodes
        description: Enter information to size your cluster
        items:
        - name: clusterNodeCount
          controlType: singleInput
          type: integer
          path: ".spec.parameters.nodes.count"
          title: Node Count
          description: Number of nodes in the cluster
          default: 1
          validation:
          - minimum: 1
          - maximum: 100
          - required: true
            customError: Node count is required.
        - name: clusterNodeSize
          controlType: singleSelect
          path: ".spec.parameters.nodes.size"
          title: Node Size
          description: Desired node size (small, medium, or large).
          default: small
          enum:
          - small
          - medium
          - large
          validation:
          - required: true
            customError: Node size is required.
      - title: Cluster Charts
        description: Configure cluster charts and operators
        items:
        - name: promVersion
          controlType: singleInput
          type: string
          path: ".spec.parameters.charts.operators.prometheus.version"
          title: Prometheus Chart Version
          description: The version of kube-prometheus-stack chart to install
          default: 15.0.1
          validation:
          - required: false
spec:
  group: azure.platformref.crossplane.io
  names:
    kind: XCluster
    plural: xclusters
  claimNames:
    kind: Cluster
    plural: clusters
  connectionSecretKeys:
  - kubeconfig
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
                description: ID of this Cluster that other objects will use to refer to it.
              parameters:
                type: object
                description: Cluster configuration parameters.
                properties:
                  nodes:
                    type: object
                    description: Cluster node configuration parameters.
                    properties:
                      count:
                        type: integer
                        description: Desired node count, from 1 to 100.
                      size:
                        type: string
                        description: Size of node.
                        enum:
                        - small
                        - medium
                        - large
                    required:
                    - count
                    - size
                  charts:
                    type: object
                    description: Cluster node configuration parameters.
                    properties:
                      wordpress:
                            type: object
                            description: Configuration for the Prometheus operator.
                            properties:
                              version:
                                type: string
                                description: Prometheus operator version to run.
                            required:
                            - version
                    required:
                    - wordpress   
                required:
                - nodes
                - charts
            required:
            - id
            - parameters
```

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xaks.azure.platformref.crossplane.io
  labels:
    provider: azure
spec:
  compositeTypeRef:
    apiVersion: azure.platformref.crossplane.io/v1alpha1
    kind: XAKS
  resources:
    - base:
      apiVersion: containerservice.azure.jet.crossplane.io/v1alpha2
      kind: KubernetesCluster
      spec:
        forProvider:
          location: East US 2
          version: "" #If blank, uses regions's default version
          defaultNodePool:
            name: default
    patches:
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
        transforms:
          - type: string
            string:
              fmt: "%s-aks"
      - fromFieldPath: spec.id
        toFieldPath: metadata.annotations[crossplane.io/external-name]
        transforms:
          - type: string
            string:
              fmt: "%s-aks"
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.resourceGroupNameSelector.matchLabels[azure.platformref.crossplane.io/app]
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.defaultNodePool.vnetSubnetIDSelector.matchLabels[azure.platformref.crossplane.io/app]
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.dnsNamePrefix
      - fromFieldPath: spec.parameters.nodes.size
        toFieldPath: spec.forProvider.defaultNodePool.nodeVMSize
        transforms:
          - type: map
            map:
              small: Standard_B2s
              medium: Standard_B4ms
              large: Standard_B8ms
      - fromFieldPath: "spec.parameters.nodes.count"
        toFieldPath: "spec.forProvider.defaultNodePool.nodeCount"
      - fromFieldPath: spec.writeConnectionSecretToRef.namespace
        toFieldPath: spec.writeConnectionSecretToRef.namespace
      - fromFieldPath: spec.writeConnectionSecretToRef.name
        toFieldPath: spec.writeConnectionSecretToRef.name
        transforms:
          - type: string
            string:
              fmt: "%s-aks"
    connectionDetails:
      - fromConnectionSecretKey: kubeconfig
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: ProviderConfig
        spec:
          credentials:
            source: Secret
            secretRef:
              key: kubeconfig
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
        - fromFieldPath: spec.writeConnectionSecretToRef.namespace
          toFieldPath: spec.credentials.secretRef.namespace
        # This ProviderConfig uses the above AKS cluster's connection secret as
        # its credentials secret.
        - fromFieldPath: spec.writeConnectionSecretToRef.name
          toFieldPath: spec.credentials.secretRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-aks"
      readinessChecks:
        - type: None
  ```

### What environment did it happen in?

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro17,1
  Chip:	Apple M1
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	16 GB
  System Firmware Version:	7429.81.3
  OS Loader Version:	7429.81.3

  UP v0.7.0
