### ISSUE TITLE
xpls shows error for required fields that are added by a patch

### ISSUE THREAD

**Issue by muvaf** [upbound/up#271]
### What happened?

When a field is required and added as patch, `xpls` thinks it's an error.

### How can we reproduce it?

```yaml
    - name: keyring
      base:
        apiVersion: kms.gcp.upbound.io/v1beta1
        kind: KeyRing
        spec:
          forProvider: {}
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.location
          toFieldPath: spec.forProvider.location
```

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/7584126/198936364-17bd0c4f-9bef-41f3-9901-c98f4c005029.png">

### What environment did it happen in?

up v0.14.0
VSCode Upbound plugin v0.0.5
Upbound GCP Provider v0.16.0
