### ISSUE TITLE
package.yaml has empty controller image even if it is not given by user

### ISSUE THREAD

**Issue by muvaf** [upbound/up#321]
### What happened?

I got an error deploying my provider built with `v0.16.0` : `...spec.containers[0].image: required value` which is surprising because it should be the package itself since I didn't give any package URL [in the repo](https://github.com/upbound/provider-dummy/blob/main/package/crossplane.yaml) similar to other providers. When I extracted `/package.yaml` from the package, I saw the following:
```yaml
---
apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  ...
  creationTimestamp: null
  name: provider-dummy
spec:
  controller:
    image: ""
```

When I downgrade to `v0.15.0`, the problem disappears. I assume we made a change in between that defaulted `spec.controller.image` and `metadata.creationTimestamp` to their zero-values.

### How can we reproduce it?

Build a provider package with `v0.16.0`. Then run it with classic `docker run -d` and while it's running, extract `package.yaml` with `docker cp <container hash>:/package.yaml /tmp/package.yaml` and see the beginning of that file.

### What environment did it happen in?

up `v0.16.0`
