### ISSUE TITLE
Latest up version doesn't add regexp patches to the package.yaml file

### ISSUE THREAD

**Issue by ezgidemirel** [upbound/up#329]
### What happened?

I tried to build [platform-ref-gcp](https://github.com/upbound/platform-ref-gcp) with up version v.0.16.1 and noticed that patch command is missing the reg expression rule like below:
```yaml
      - fromFieldPath: status.atProvider.id
        policy:
          fromFieldPath: Required
        toFieldPath: status.gke.project
        transforms:
        - string:
            type: Regexp
          type: string
        type: ToCompositeFieldPath
```
correct patch:
```yaml
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.gke.project
          transforms:
            - type: string
              string:
                type: Regexp
                regexp:
                  match: projects\/(.+)\/serviceAccounts\/.*
                  group: 1
          policy:
            fromFieldPath: Required
```

Epic #

### How can we reproduce it?

Build the configuration with the command below:
```
up xpkg build --name ezgi-platform-ref-gcp.xpkg --package-root=package --examples-root=examples
```

### What environment did it happen in?

up cli version v0.16.1
